version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - backend/.env
    ports:
      - "5050:5000"
    networks:
      - app-network
    # depends_on:
    #   - db

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - app-network
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: lxc-nginx
    # ports:
    #   - "80:80"
    #   - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - frontend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: lxc-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet --post-hook \"nginx -s reload\"; sleep 12h & wait $${!}; done'"
    networks:
      - app-network

 

volumes:
  # postgres_data:
  certbot-etc:
  certbot-webroot:

networks:
  app-network:
